### ISSUE TITLE
Website scanning

### ISSUE THREAD

**Issue by Colliedog** [ThreatConnect-Inc/threatconnect-playbooks#81]
What I would like to do is scan our websites for script injection such as the BA magecart attack.  Will this playbook work on a website that uses dynamic pages built at runtime?  My presumption is that this for this attack to work the script has to be added to the static page so will be detectable?

**Comment by jhurd-tc** [comment]
Hi @Colliedog , great question! The [page monitor](https://github.com/ThreatConnect-Inc/threatconnect-playbooks/tree/master/playbooks/page-monitor-playbook) playbook as it is currently implemented will only work for static sites (this is because the playbook requests the site's content and records the hash of the entire site's content; for a dynamic site, the hash is probably going to be different each time the playbook requests the site).
